### ISSUE TITLE
Testing on Ubuntu Mozc

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/emoji-ime-dictionary#11]

**Comment by shuuji3** [comment]
こんにちは。Ubuntuでの動作検証を行ったので報告します。

**検証環境**

```shell
> hostnamectl
   Static hostname: precision-1
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: 3f3e83ce8f224eebb1e989b08e271416
           Boot ID: c2dcbd03c7f74ee89b3f7418e32108c2
  Operating System: Ubuntu 20.04 LTS
            Kernel: Linux 5.4.0-39-generic
      Architecture: x86-64
```

**検証した辞書**

[Release 最新の絵文字辞書を公開 · peaceiris/emoji-ime-dictionary](https://github.com/peaceiris/emoji-ime-dictionary/releases/tag/v1.0.2) にある`emoji.zip`を使用しました。

**検証の手順**

[辞書の導入方法 - Installation / Google 日本語入力](https://github.com/peaceiris/emoji-ime-dictionary#google-%E6%97%A5%E6%9C%AC%E8%AA%9E%E5%85%A5%E5%8A%9B) と同じ手順を実行することでインポートできました。

インポート後にダイアログに次のメッセージが表示されました。「6610 entries are imported to emoji-ime-dictionary.」

**Comment by peaceiris** [comment]
@shuuji3 ありがとうございます!

Ubuntu 20.04 での検証はやっていなかったので助かりました。([google/mozc](https://github.com/google/mozc) が最近メンテされてないのが気になりますね...)

**Comment by peaceiris** [comment]
https://github.com/peaceiris/emoji-ime-dictionary/releases/tag/v2.0.2

ベースのデータセットを更新しました。
詳細はこちら 👉 [絵文字の日本語読み辞書をUnicode 12.0対応に更新しました - Out-of-the-box](https://yag-ays.github.io/project/emoji-ja-update-12/)
