### ISSUE TITLE
Add: emoji dictionary for ATOK

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/emoji-ime-dictionary#15]
ATOK も絵文字変換はできるが表現力に乏しいので、やっぱり ATOK 用の辞書も用意する。

**Comment by ityuki** [comment]
ATOKで辞書を使ってみました。

1. 適当なバージョンのemozi.zipをダウンロード
1. UTF-16,CR+LF,BOM有りに変更
1. 「記号」を「独立語」に置換
1. ATOKで辞書登録

でとりあえず通りましたので、ご参考までに。

**Comment by peaceiris** [comment]
おお、ありがとうございます!

**Comment by peaceiris** [comment]
https://github.com/peaceiris/emoji-ime-dictionary/releases/tag/v2.2.0

- ベースのデータセットを更新
- `ゔ` を `う゛` に置換 (Close #8 by #24 )
- Microsoft IME 形式の辞書を release assets に追加
- ATOK 形式の辞書を release assets に追加

しました。
