### ISSUE TITLE
Microsoft IME での検証

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/emoji-ime-dictionary#4]
私が Windows を持っていないため検証できていません。どなたか検証をお願いします。

- 改行コードで問題があるかも

**Comment by logroid** [comment]
Windows 10 / MS IME 2012 (15.0.9600.18514) での検証です。

1.  emoji.txt を UTF-16 LE BOM付き&CRLF に変換
```console
# nkf --version
Network Kanji Filter Version 2.1.4 (2015-12-12)
Copyright (C) 1987, FUJITSU LTD. (I.Ichikawa).
Copyright (C) 1996-2015, The nkf Project.
# nkf -W8 -w16L -Lw -- emoji.txt > emoji_u16le.txt
```
1. ユーザ辞書ツール の ツールメニュー -> テキストファイルからの登録 で、変換した emoji_u16le.txt を指定
1. 取り込み完了

「ゔぁーさす」を「ばーさす」、「ゔぃえす」を「ぶいえす」にすると重複するため、その2つは取り込みエラーになりました。

**Comment by peaceiris** [comment]
@logroid さん

検証ありがとうございます!

`nkf` での変換方法も教えていただき、すごく助かります。次のリリースで用意する Windows 用の辞書はこれで生成しようと思います。

> 「ゔぁーさす」を「ばーさす」、「ゔぃえす」を「ぶいえす」にすると重複するため、その2つは取り込みエラーになりました。

`ゔ` ではなくて `う゛(vu)` なら入力できるので、`ゔ` は `う゛(vu)` に置換しようと思います。

**Comment by lulzneko** [comment]
Microsoft Windows 10 Enterprise ＆ emoji-ime-dictionary v1.0.2 です。

**登録について**
@logroid さん の方法 で エラーなしで全登録できました。
「ゔぁーさす」などの「ゔ」につきましも問題なく登録できました。

**「ゔ」につてい**
@maymehdell さん の レポート 操作２ と 同じで変換が必要でした。
ひらがなの「ゔ」を入力する方法がなく「ヴぁ」が入力になるため候補にならないようです。
「：ヴぁーさす」のように「ヴ」の読みを登録すると変換できました。


以上、ご報告となります。
素晴らしい辞書の公開ありがとうございます👍

**Comment by peaceiris** [comment]
@lulzneko さん、検証ありがとうございます!

> **登録について**
> @logroid さん の方法 で エラーなしで全登録できました。
> 「ゔぁーさす」などの「ゔ」につきましも問題なく登録できました。

お二人の環境で問題ないようなので Windows 用辞書の生成にその方法を採用します!

> **「ゔ」について**
> @maymehdell さん の レポート 操作２ と 同じで変換が必要でした。
> ひらがなの「ゔ」を入力する方法がなく「ヴぁ」が入力になるため候補にならないようです。
> 「：ヴぁーさす」のように「ヴ」の読みを登録すると変換できました。

変換しておきます。

**Comment by peaceiris** [comment]
[Release 日本語 IME 絵文字拡張辞書 v2.1.0 · peaceiris/emoji-ime-dictionary](https://github.com/peaceiris/emoji-ime-dictionary/releases/tag/v2.1.0)

- ベースの辞書を更新
- `ゔ` を `う゛` に置換 (Close #8 by #24 )
- Microsoft IME 形式の辞書を release assets に追加

しました。
